
export const VIDEO_UPLOAD_REQUEST = 'VIDEO_UPLOAD_REQUEST';
export const VIDEO_UPLOAD_SUCCESS = 'VIDEO_UPLOAD_SUCCESS';
export const VIDEO_UPLOAD_FAIL = 'VIDEO_UPLOAD_FAIL';

export const VIDEO_LIST_REQUEST = 'VIDEO_LIST_REQUEST';
export const VIDEO_LIST_SUCCESS = 'VIDEO_LIST_SUCCESS';
export const VIDEO_LIST_FAIL = 'VIDEO_LIST_FAIL';

export const VIDEO_DETAILS_REQUEST = 'VIDEO_DETAILS_REQUEST';
export const VIDEO_DETAILS_SUCCESS = 'VIDEO_DETAILS_SUCCESS';
export const VIDEO_DETAILS_FAIL = 'VIDEO_DETAILS_FAIL';


export const VIDEO_LIKE_REQUEST = 'VIDEO_LIKE_REQUEST';
export const VIDEO_LIKE_SUCCESS = 'VIDEO_LIKE_SUCCESS';
export const VIDEO_LIKE_FAIL = 'VIDEO_LIKE_FAIL';

export const VIDEO_DISLIKE_REQUEST = 'VIDEO_DISLIKE_REQUEST';
export const VIDEO_DISLIKE_SUCCESS = 'VIDEO_DISLIKE_SUCCESS';
export const VIDEO_DISLIKE_FAIL = 'VIDEO_DISLIKE_FAIL';

export const SUCCESSVID_CHANGE = 'SUCCESSVID_CHANGE';