
export const VIDEO_UPLOAD_REQUEST = 'VIDEO_UPLOAD_REQUEST';
export const VIDEO_UPLOAD_SUCCESS = 'VIDEO_UPLOAD_SUCCESS';
export const VIDEO_UPLOAD_FAIL = 'VIDEO_UPLOAD_FAIL';

export const VIDEO_LIST_REQUEST = 'VIDEO_LIST_REQUEST';
export const VIDEO_LIST_SUCCESS = 'VIDEO_LIST_SUCCESS';
export const VIDEO_LIST_FAIL = 'VIDEO_LIST_FAIL';